apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prueva-bk  # Aquí he cambiado "Prueva BK" a "prueva-bk"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: Juanlu1411
